version: 0.0
os: linux
files:
  - source: /node_react_crud/backend
    destination: /home/ubuntu/app/backend
  - source: /node_react_crud/frontend
    destination: /home/ubuntu/app/frontend
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
