    - name: Install Mysql
      package:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - python3-mysqldb
        - libmysqlclient-dev


    - name: Create MySQL user
      mysql_user:
        name: "{{ DB_USERNAME }}"
        password: "{{DB_PASSWORD}}"
        priv: "*.*:ALL"
        host: "{{DB_SERVER}}"
        state: present


    - name: Check if database exists
      mysql_db:
        name: "{{ DB_NAME }}"
        state: present
      register: db_exists


    - name: Create database
      mysql_db:
        name: "{{ DB_NAME }}"
        state: present
      when: not db_exists.changed


    # - name: Check if database is empty
    #   command: mysql -u root -p{{ DB_PASSWORD }} -e "USE {{ DB_NAME }}; SHOW TABLES;"
    #   register: db_tables
    #   changed_when: false
    #   failed_when: db_tables.stdout != ''
    #   becomes: true


    # - name: Debug - Show database tables output  ##
    #   debug:
    #     var: db_tables.stdout


    # - name: Restore database
    #   mysql_db:
    #     name: "{{ DB_NAME }}"
    #     state: import
    #     target: /home/ubuntu/Node_Project/db.sql
    #   when: db_tables.stdout == ''

    - name: Create MySQL user
      mysql_user:
        name: "{{ DB_USERNAME }}"
        password: "{{ DB_PASSWORD }}"
        priv: "*.*:ALL"
        host: localhost
        state: present

    - name: Import database dump into test_db
      mysql_db:
        name: "{{DB_NAME}}"
        state: import
        target: /home/ubuntu/Node_Project/db.sql