plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
hostnames:
  - instance-id
groups:
  Dev: "'prashansa_terraform_ec2' in tags.Name"
filters:
  tag:Name: "prashansa_terraform_ec2"
  instance-state-name: running